//! Candidate-generation and index maintenance seams.
//!
//! Owns the FTS5 lexical index, namespace prefilter indexes, and
//! the index maintenance contract for rebuild and health checks.

use crate::api::NamespaceId;
use crate::types::{CanonicalMemoryType, MemoryId, SessionId};

// ── Index types ──────────────────────────────────────────────────────────────

/// Supported index families for candidate generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IndexFamily {
    /// FTS5 full-text lexical index.
    Fts5Lexical,
    /// Namespace prefilter index for fast scope narrowing.
    NamespacePrefilter,
    /// Fingerprint deduplication index.
    FingerprintDedup,
    /// Session-scoped temporal index.
    SessionTemporal,
    /// Memory-type categorical index.
    MemoryTypeCategorical,
}

impl IndexFamily {
    /// Stable machine-readable name.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Fts5Lexical => "fts5_lexical",
            Self::NamespacePrefilter => "namespace_prefilter",
            Self::FingerprintDedup => "fingerprint_dedup",
            Self::SessionTemporal => "session_temporal",
            Self::MemoryTypeCategorical => "memory_type_categorical",
        }
    }
}

// ── Index entry ──────────────────────────────────────────────────────────────

/// Entry to be inserted into an FTS5 lexical index.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Fts5IndexEntry {
    /// Memory this entry indexes.
    pub memory_id: MemoryId,
    /// Namespace scope for prefiltering.
    pub namespace: NamespaceId,
    /// Session scope for temporal prefiltering.
    pub session_id: SessionId,
    /// Memory type for categorical prefiltering.
    pub memory_type: CanonicalMemoryType,
    /// Compact text content for full-text indexing.
    pub content: String,
    /// Fingerprint for deduplication.
    pub fingerprint: u64,
    /// Normalization generation for cache invalidation.
    pub normalization_generation: &'static str,
}

/// Candidate generated by an index lookup.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IndexCandidate {
    /// Memory id of the candidate.
    pub memory_id: MemoryId,
    /// Which index produced this candidate.
    pub source_index: IndexFamily,
    /// Relevance score from the index (0..1000).
    pub index_score: u16,
    /// Namespace of the candidate.
    pub namespace: NamespaceId,
}

// ── Index query ──────────────────────────────────────────────────────────────

/// Query against the FTS5 lexical index.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Fts5Query {
    /// Search terms for the FTS5 MATCH expression.
    pub terms: String,
    /// Namespace filter (required).
    pub namespace: NamespaceId,
    /// Optional session scope filter.
    pub session_filter: Option<SessionId>,
    /// Optional memory type filter.
    pub memory_type_filter: Option<CanonicalMemoryType>,
    /// Maximum candidates to return.
    pub limit: usize,
}

impl Fts5Query {
    /// Builds a basic namespace-scoped FTS5 query.
    pub fn new(terms: impl Into<String>, namespace: NamespaceId, limit: usize) -> Self {
        Self {
            terms: terms.into(),
            namespace,
            session_filter: None,
            memory_type_filter: None,
            limit,
        }
    }

    /// Adds a session filter.
    pub fn with_session(mut self, session_id: SessionId) -> Self {
        self.session_filter = Some(session_id);
        self
    }

    /// Adds a memory type filter.
    pub fn with_memory_type(mut self, memory_type: CanonicalMemoryType) -> Self {
        self.memory_type_filter = Some(memory_type);
        self
    }
}

// ── Index health ─────────────────────────────────────────────────────────────

/// Health status of one index.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IndexHealth {
    Healthy,
    Stale,
    NeedsRebuild,
    Missing,
}

impl IndexHealth {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Healthy => "healthy",
            Self::Stale => "stale",
            Self::NeedsRebuild => "needs_rebuild",
            Self::Missing => "missing",
        }
    }
}

/// Health report for a specific index.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IndexHealthReport {
    pub family: IndexFamily,
    pub health: IndexHealth,
    pub entry_count: usize,
    pub generation: &'static str,
}

// ── Index trait ──────────────────────────────────────────────────────────────

/// Core index contract for candidate generation.
pub trait IndexApi {
    /// Returns the stable component identifier.
    fn api_component_name(&self) -> &'static str;

    /// Returns health reports for all managed indexes.
    fn health_reports(&self) -> Vec<IndexHealthReport>;

    /// Returns the set of index families this module manages.
    fn managed_families(&self) -> &[IndexFamily];
}

// ── Engine ───────────────────────────────────────────────────────────────────

/// Stable index boundary owned by `membrain-core`.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub struct IndexModule;

impl IndexModule {
    /// All index families managed by the core index module.
    const MANAGED_FAMILIES: &'static [IndexFamily] = &[
        IndexFamily::Fts5Lexical,
        IndexFamily::NamespacePrefilter,
        IndexFamily::FingerprintDedup,
        IndexFamily::SessionTemporal,
        IndexFamily::MemoryTypeCategorical,
    ];

    /// Returns the stable component identifier for this index surface.
    pub const fn component_name(&self) -> &'static str {
        "index"
    }
}

impl IndexApi for IndexModule {
    fn api_component_name(&self) -> &'static str {
        "index"
    }

    fn health_reports(&self) -> Vec<IndexHealthReport> {
        Self::MANAGED_FAMILIES
            .iter()
            .map(|&family| IndexHealthReport {
                family,
                health: IndexHealth::Healthy,
                entry_count: 0,
                generation: "v0.1",
            })
            .collect()
    }

    fn managed_families(&self) -> &[IndexFamily] {
        Self::MANAGED_FAMILIES
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn index_module_manages_all_families() {
        let module = IndexModule;
        let families = module.managed_families();
        assert_eq!(families.len(), 5);
        assert!(families.contains(&IndexFamily::Fts5Lexical));
        assert!(families.contains(&IndexFamily::NamespacePrefilter));
    }

    #[test]
    fn health_reports_cover_all_families() {
        let module = IndexModule;
        let reports = module.health_reports();
        assert_eq!(reports.len(), 5);
        assert!(reports.iter().all(|r| r.health == IndexHealth::Healthy));
    }

    #[test]
    fn fts5_query_builder() {
        let ns = NamespaceId::new("test").unwrap();
        let query = Fts5Query::new("hello world", ns.clone(), 10)
            .with_session(SessionId(7))
            .with_memory_type(CanonicalMemoryType::Event);

        assert_eq!(query.terms, "hello world");
        assert_eq!(query.namespace, ns);
        assert_eq!(query.session_filter, Some(SessionId(7)));
        assert_eq!(query.memory_type_filter, Some(CanonicalMemoryType::Event));
        assert_eq!(query.limit, 10);
    }
}
